package com.example.botdemo.domain;

public enum UserState {
    REGISTRATION_ADD_PHOTO,
    REGISTRATION_AGE,
    REGISTRATION_CITY,
    REGISTRATION_NAME,
    REGISTRATION_GENDER,
    REGISTRATION_DETAILS,
    REGISTRATION_INTERESTED_GENDER,
    REGISTRATION_INTERESTED_AGE,
    REGISTRATION_PHOTOS,
    REGISTRATION_CONTACTS,
    REGISTRATION_SAVE,
}
